<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the commercial license
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category Extait
 * @package Extait_WidgetsTransfer
 * @copyright Copyright (c) 2016-2018 Extait, Inc. (http://www.extait.com)
 */

// @codingStandardsIgnoreFile

/** @var \Extait\WidgetsTransfer\Block\Adminhtml\HiddenMenuItems $block */
?>

<script type="text/javascript">
    var conf = <?= /* @escapeNotVerified */ $block->getConfig() ?>;

    require(['jquery'], function ($) {
        $(function () {
            var $widgets = $('.admin__menu .item-cms-widget-instance'),
                $widgetsPro = $('.admin__menu .item-extait-widget-instance').hide();

            if (conf.isModuleEnabled === true) {
                $widgetsPro.show();

                if (conf.isAllowedDisplayingDefaultPage === false) {
                    $widgets.hide();
                }
            }
        });
    });
</script>
